version: '3.8'

services:
  database:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - .env
    ports:
      - "5432:5432"

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_LISTENER_NAMES: INSIDE,OUTSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:7075
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:7075
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "7075:7075"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
